# -- Groups to display on the portal page
# @default -- List of groups (see [values.yaml](values.yaml))
groups:
  - name: First Group
    visible: true
    color: gray-700
    groups:
      - name: Sub Group 1.1
        color: blue-500
        links:
          - name: Vue.js
            url: https://vuejs.org/
          - name: tailwindcss
            url: https://tailwindcss.com/
      - name: Sub Group 1.2
        color: red-500
        links:
          - name: Apple
            url: https://www.apple.com/
          - name: Android
            url: https://www.android.com/
      - name: Sub Group 1.3
        color: yellow-700
        links:
          - name: Google
            url: https://www.google.com/
          - name: Microsoft
            url: https://www.microsoft.com
  - name: Second Group
    visible: false
    color: blue-400
    groups:
      - name: Sub Group 2.1
        color: blue-700
        links:
          - name: Netflix
            url: https://www.netflix.com/

authorization:
  # -- Require authorization to access the portal page
  enabled: false
  # -- Secret used to encrypt cookies
  cookieSecret:
  # -- OIDC provider (see [documentation](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider))
  provider: keycloak-oidc
  # -- URL of the OIDC issuer
  issuerUrl:
  # -- OIDC client id
  clientId:
  # -- OIDC client secret
  clientSecret:
  # -- External address of the protected service (used as redirect URI)
  externalAddress: http://chart-example.local

# -- Number of replicas
replicaCount: 1

image:
  oauth:
    # -- Image to use if authorization is required
    repository: quay.io/oauth2-proxy/oauth2-proxy
    # -- Tag to use if authorization is required
    tag: v7.3.0
  nginx:
    # -- Image to use without authorization
    repository: nginx
    # -- Tag to use without authorization
    tag: 1.23-alpine
  # -- Image pull policy
  pullPolicy: IfNotPresent

# -- Image pull secrets for the pod
imagePullSecrets: []

# -- Override name of this release
nameOverride: ""

# -- Override full name of this release
fullnameOverride: ""

# -- Annotations to be added to the pod
podAnnotations: {}

service:
  # -- Service type
  type: ClusterIP
  # -- Service port
  port: 80

ingress:
  # -- Enable ingress
  enabled: false
  # -- Ingress class name
  className: ""
  # -- Annotations to be added to ingress
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress host configuration
  # @default -- List of hosts and paths for the ingress (see [values.yaml](values.yaml))
  hosts:
    # @ignore
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- TLS configuration for the ingress
  # @default List of hosts and secrets (see [values.yaml](values.yaml))
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Container resources (see [Kubernetes docs](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits))
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Node selector for pods (see [Kubernetes docs](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector))
nodeSelector: {}

# -- Tolerations for pods (see [Kubernetes docs](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/))
tolerations: []

# -- Affinity for pods (see [Kubernetes docs](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity))
affinity: {}
