{{- if .Values.authorization.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "startpage.fullname" . }}
  labels:
    {{- include "startpage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "startpage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/data: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "startpage.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: startpage
          image: {{ .Values.image.oauth.repository }}:{{ .Values.image.oauth.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "startpage.fullname" . }}-oauth
          env:
            - name: OAUTH2_PROXY_UPSTREAMS
              value: file:///startpage/#/
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: 0.0.0.0:80
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: "*"
            - name: OAUTH2_PROXY_SILENCE_PING_LOGGING
              value: "true"
            - name: OAUTH2_PROXY_PROVIDER
              value: {{ .Values.authorization.provider }}
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: {{ .Values.authorization.externalAddress }}/oauth2/callback
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: {{ .Values.authorization.issuerUrl }}
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: "true"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          volumeMounts:
            - name: data
              mountPath: /startpage
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          configMap:
            name: {{ include "startpage.fullname" . }}
{{- end -}}
