{{ if .Values.authorization.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "startpage.fullname" . }}-oauth
  labels:
    {{- include "startpage.labels" . | nindent 4 }}
type: Opaque
data:
  OAUTH2_PROXY_COOKIE_SECRET: {{ default (randAlphaNum 32) .Values.authorization.cookieSecret | b64enc | quote }}
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.authorization.clientId | b64enc | quote }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.authorization.clientSecret | b64enc | quote }}
{{- end }}